# Generated by Django 2.2.12 on 2022-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('surname', models.CharField(max_length=200, verbose_name='Familiya')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Elektron pochta')),
                ('pasword', models.CharField(max_length=100, verbose_name='Parol')),
            ],
        ),
    ]
